### ISSUE TITLE
Add a system console support for Webviz

### ISSUE THREAD

**Issue by zzangjinsun** [3secondz-lab/milliways#17]
Add a system console panel in the Webviz

**Comment by crazy4u2** [comment]
- [x] get_node_list.js api 화 완료. (/api/getNodes)
- [ ] "/api/getNodes" ==> webviz 프로젝트에 추가.

**Comment by crazy4u2** [comment]
```
[
  {
    Node : "/webviz_test_server/parameter_descriptions",
    [
      {Name : amplitude, Type : double, Level : 0, Desc : "블라블라", Max : 5, Min : 0, Default : 1},
      {Name : freq, Type : double, Level : 0, Desc : "블라블라", Max : 100, Min : 0, Default : 1},
    ]
  }
]
```

같은 식으로 데이터 구성(api 출력)을 해야함.

**Comment by crazy4u2** [comment]
api 출력에 알맞는 구성으로 코드개선 완료 
e7f0b58

**Comment by crazy4u2** [comment]
nodejs 에서 굴러갈 수 있게 만든 후 webviz 에 추가하는 작업 필요

**Comment by crazy4u2** [comment]
- [x] 해당 프로젝트의 webpack 구조와 소스 구조 파악
- [ ] panel list 업데이트
- [ ] system console panel component 작성

**Comment by crazy4u2** [comment]
webviz 레파지토리에 리눅스 터미널 구현됨.
옵션 같은 것 설정하는 부분 삭제해야하는 작업이 남아있음.

**Comment by crazy4u2** [comment]
production mode 에서 쓸 수 있게 코드 작성중
