### ISSUE TITLE
GUI 추가를 위한 작업 필요

### ISSUE THREAD

**Issue by crazy4u2** [3secondz-lab/milliways#22]
NodeList 구하는 로직을 api 서버가 내려주는 식으로 내용 추가 필요.
- [x] NodeList 출력 구조 e7f0b58 
- [ ] webviz에 api 하여 추가 필요.

**Comment by crazy4u2** [comment]
```
[
  {
    Node : "/webviz_test_server/parameter_descriptions",
    List : [
      {Name : amplitude, Type : double, Level : 0, Desc : "블라블라", Max : 5, Min : 0, Default : 1},
      {Name : freq, Type : double, Level : 0, Desc : "블라블라", Max : 100, Min : 0, Default : 1},
    ]
  }
]
```
이렇게 출력됨.

**Comment by crazy4u2** [comment]
- [ ] 새로 전달받은 NodeList 추출 로직을 API 화 하여 작성
- [ ] GUI 작성
- [ ] GUI 에서 보내는 커맨드를 시스템 콘솔에서 입력을 넣는 것처럼 변경하는 로직(API 화) 작성

**Comment by zzangjinsun** [comment]
PR #25 를 통해 roslibjs API 를 이용한 parameter 변경 예제를 추가해 두었으니 참고하시면 될 것 같습니다.
